# Generated by Django 4.2.7 on 2024-05-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=500, null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(max_length=500, null=True, upload_to='', verbose_name='cover image'),
        ),
    ]
