# Generated by Django 4.2.7 on 2024-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_avatar_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(max_length=500, null=True, upload_to='account/profile_avatar_images/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(max_length=500, null=True, upload_to='account/profile_cover_images/', verbose_name='cover image'),
        ),
    ]
