# Generated by Django 4.2.7 on 2024-05-30 08:23

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_avatar_alter_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.user_avatar, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.user_cover_image, verbose_name='cover image'),
        ),
    ]
