# Generated by Django 4.2.7 on 2024-05-06 07:29

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otptoken_options_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.user_avatar, verbose_name='avatar'),
        ),
    ]
