# Generated by Django 4.2.7 on 2024-05-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_birthday_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('De-active', 'De-active'), ('Not Verified', 'Not Verified')], default='Not Verified', max_length=20, verbose_name='status'),
        ),
    ]
