# Generated by Django 4.2.7 on 2024-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='cover image'),
        ),
    ]
