# Generated by Django 4.2.7 on 2024-05-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_bio_user_facebook_user_instagram_user_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='channel category name')),
            ],
            options={
                'verbose_name': 'Channel Category',
                'verbose_name_plural': 'Channel Categories',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='channel_categories', to='account.channelcategory'),
        ),
    ]
