# Generated by Django 4.2.7 on 2024-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_channelcategory_user_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='channel_categories', to='account.channelcategory'),
        ),
    ]
