# Generated by Django 4.2.7 on 2024-07-05 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('room_id', models.CharField(max_length=100, unique=True, verbose_name='room id')),
                ('room_name', models.CharField(max_length=255, verbose_name='room name')),
                ('user_name', models.CharField(max_length=255, verbose_name='user name')),
                ('cover_image', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='cover image')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
            },
        ),
    ]
