# Generated by Django 4.2.7 on 2024-07-06 09:44

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='cover_image',
            field=models.ImageField(default=1, max_length=500, upload_to=services.uploader.Uploader.stream_image, verbose_name='cover image'),
            preserve_default=False,
        ),
    ]
