# Generated by Django 5.0.7 on 2024-09-21 12:39

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(max_length=2000, upload_to=services.uploader.Uploader.slider_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='cover_image',
            field=models.ImageField(max_length=2000, upload_to=services.uploader.Uploader.stream_image, verbose_name='cover image'),
        ),
    ]
