# Generated by Django 4.2.7 on 2024-07-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('core', '0003_alter_stream_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stream_products', to='product.product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
