# Generated by Django 4.2.7 on 2024-07-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('core', '0004_stream_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_products', to='product.product', verbose_name='product'),
        ),
    ]
