# Generated by Django 4.2.7 on 2024-07-04 09:43

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('in_sale', models.BooleanField(default=False, verbose_name='In Sale')),
                ('percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Percent')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Final Price')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Like Count')),
                ('is_premium', models.BooleanField(default=False, verbose_name='is premium')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number')),
                ('product_link', models.CharField(blank=True, max_length=254, null=True, verbose_name='product link')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('location_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Location URL')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like Count')),
            ],
            options={
                'verbose_name': 'Product Comment',
                'verbose_name_plural': 'Product Comments',
            },
        ),
        migrations.CreateModel(
            name='ProductCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product Comment Like',
                'verbose_name_plural': 'Product Comments Like',
            },
        ),
        migrations.CreateModel(
            name='ProductPropertyAndValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_property', models.CharField(max_length=255, verbose_name='Property')),
                ('property_value', models.CharField(max_length=255, verbose_name='Property Value')),
            ],
            options={
                'verbose_name': 'Product Property & Value',
                'verbose_name_plural': 'Product Property & Value',
            },
        ),
        migrations.CreateModel(
            name='ProductVideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_type', models.CharField(choices=[('Video', 'Video'), ('Shorts', 'Shorts')], max_length=255, verbose_name='Product Type')),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.product_cover_image, verbose_name='Cover Image')),
                ('original_video', models.FileField(max_length=500, upload_to=services.uploader.Uploader.product_original_video, verbose_name='Original Video')),
                ('compressed_video', models.FileField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.product_compress_video, verbose_name='Compressed Video (480p)')),
            ],
            options={
                'verbose_name': 'Product Video & Type',
                'verbose_name_plural': 'Product Videos & Types',
            },
        ),
        migrations.CreateModel(
            name='UserProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ManyToManyField(related_name='user_product_like', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Products Like',
            },
        ),
    ]
