# Generated by Django 4.2.7 on 2024-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideotype',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='productvideotype',
            name='video_url',
        ),
        migrations.AddField(
            model_name='productvideotype',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='productvideotype',
            name='video',
            field=models.FileField(default=1, max_length=255, upload_to='', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
