# Generated by Django 5.0.7 on 2024-08-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_child', to='product.productcomment', verbose_name='Parent Comment'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='productcommentlike',
            name='product_comment',
            field=models.ManyToManyField(related_name='user_product_comment_like', to='product.productcomment', verbose_name='Product Comment'),
        ),
        migrations.AddField(
            model_name='productcommentlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='productpropertyandvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_property_and_values', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productvideotype',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_video_type', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='userproductlike',
            name='product',
            field=models.ManyToManyField(related_name='user_product_like', to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='userproductlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='product_cat_name_4f76a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['user', 'product'], name='product_pro_user_id_bd6a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='productcommentlike',
            index=models.Index(fields=['user'], name='product_pro_user_id_02bbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='productpropertyandvalue',
            index=models.Index(fields=['product'], name='product_pro_product_73bc62_idx'),
        ),
        migrations.AddIndex(
            model_name='productvideotype',
            index=models.Index(fields=['product_type'], name='product_pro_product_b6bc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='userproductlike',
            index=models.Index(fields=['user'], name='product_use_user_id_660ad1_idx'),
        ),
    ]
