# Generated by Django 4.2.7 on 2024-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productvideotype_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideotype',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='product/cover_images/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='productvideotype',
            name='video',
            field=models.FileField(max_length=255, upload_to='product/videos/', verbose_name='Video'),
        ),
    ]
