# Generated by Django 4.2.7 on 2024-05-30 13:51

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvideotype_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvideotype',
            name='video',
        ),
        migrations.AddField(
            model_name='productvideotype',
            name='compressed_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=services.uploader.Uploader.product_compress_video, verbose_name='Compressed Video (480p)'),
        ),
        migrations.AddField(
            model_name='productvideotype',
            name='original_video',
            field=models.FileField(default=1, max_length=255, upload_to=services.uploader.Uploader.product_original_video, verbose_name='Original Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvideotype',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=services.uploader.Uploader.product_cover_image, verbose_name='Cover Image'),
        ),
    ]
