# Generated by Django 5.0.7 on 2024-09-21 13:00

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvideotype_compressed_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideotype',
            name='original_video',
            field=models.FileField(max_length=5000, upload_to=services.uploader.Uploader.product_original_video, verbose_name='Original Video'),
        ),
    ]
