# Generated by Django 4.2.7 on 2024-05-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_final_price_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentlike',
            name='product_comment',
        ),
        migrations.RemoveField(
            model_name='productcommentlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userproductlike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userproductlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='ProductCommentLike',
        ),
        migrations.DeleteModel(
            name='UserProductLike',
        ),
    ]
