# Generated by Django 4.2.7 on 2024-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideotype',
            name='product_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Shorts', 'Shorts')], db_index=True, max_length=255, verbose_name='Product Type'),
        ),
        migrations.AddIndex(
            model_name='productvideotype',
            index=models.Index(fields=['product_type'], name='product_pro_product_b6bc8a_idx'),
        ),
    ]
