# Generated by Django 4.2.7 on 2024-05-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productcommentlike_product_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.CreateModel(
            name='ProductVideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_type', models.CharField(choices=[('Video', 'Video'), ('Shorts', 'Shorts')], max_length=255, verbose_name='Product Type')),
                ('video_url', models.URLField(max_length=255, verbose_name='Video Url')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_video_type', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Video & Type',
                'verbose_name_plural': 'Product Videos & Types',
            },
        ),
    ]
