# Generated by Django 4.2.7 on 2024-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_product_type_remove_product_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Like Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View Count'),
        ),
    ]
