# Generated by Django 4.2.7 on 2024-06-08 18:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productvideotype_compressed_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone number'),
        ),
    ]
