# Generated by Django 4.2.7 on 2024-05-09 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_like_count_alter_product_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent'),
        ),
    ]
