# Generated by Django 4.2.7 on 2024-05-09 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_product_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Percent'),
        ),
        migrations.CreateModel(
            name='UserProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ManyToManyField(related_name='user_product_like', to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Products Like',
            },
        ),
    ]
