# Generated by Django 4.2.7 on 2024-05-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_alter_product_percent_userproductlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductlike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
