# Generated by Django 4.2.7 on 2024-06-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPropertyAndValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_property', models.CharField(max_length=255, verbose_name='Property')),
                ('property_value', models.CharField(max_length=255, verbose_name='Property Value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_property_and_values', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Property & Value',
                'verbose_name_plural': 'Product Property & Value',
            },
        ),
    ]
