# Generated by Django 4.2.7 on 2024-06-29 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productpropertyandvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='location_url',
            field=models.TextField(default=1, validators=[django.core.validators.URLValidator()], verbose_name='Location URL'),
            preserve_default=False,
        ),
    ]
