# Generated by Django 4.2.7 on 2024-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_location_product_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='product link'),
        ),
    ]
