# Generated by Django 4.2.7 on 2024-05-10 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_productcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product_comment', models.ManyToManyField(related_name='user_product_comment_like', to='product.productcomment', verbose_name='Product Comment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_like', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Comment Like',
                'verbose_name_plural': 'Product Comments Like',
            },
        ),
    ]
