# Generated by Django 4.2.7 on 2024-05-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productcommentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideotype',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Cover Image'),
        ),
    ]
