# Generated by Django 4.2.7 on 2024-05-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0013_userproducthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_A_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
