# Generated by Django 4.2.7 on 2024-05-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_userproducthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducthistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
