# Generated by Django 4.2.7 on 2024-05-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_userproducthistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProductHistory',
        ),
    ]
