# Generated by Django 4.2.7 on 2024-05-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_userproducthistory_ip_address'),
        ('product', '0015_delete_userproducthistory'),
    ]

    operations = [
    ]
