# Generated by Django 4.2.7 on 2024-05-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_alter_userproducthistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('watch_date', models.DateTimeField(auto_now=True, verbose_name='Watch')),
                ('product_video_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_video_type', to='product.productvideotype', verbose_name='Product Video Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User History',
                'verbose_name_plural': 'User History',
            },
        ),
    ]
