# Generated by Django 4.2.7 on 2024-05-26 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_alter_userproducthistory_user'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userhistory',
            unique_together={('user', 'product_video_type')},
        ),
    ]
