# Generated by Django 4.2.7 on 2024-07-05 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', 'product_video_type'], name='history_use_user_id_e598a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userhistory',
            unique_together={('user', 'product_video_type')},
        ),
    ]
