# Generated by Django 4.2.7 on 2024-05-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_userhistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='watch_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Watch date'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', 'product_video_type'], name='history_use_user_id_e598a2_idx'),
        ),
    ]
