# Generated by Django 4.2.7 on 2024-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_userhistory_watch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='watch_date',
            field=models.DateTimeField(verbose_name='Watch date'),
        ),
    ]
