# Generated by Django 4.2.7 on 2024-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_method',
            field=models.CharField(default='email', max_length=30, verbose_name='sign up method'),
        ),
    ]
