# Generated by Django 5.0.7 on 2024-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_chats_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
