# Generated by Django 5.0.7 on 2024-09-21 12:39

import services.uploader
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_loggedinuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to=services.uploader.Uploader.user_avatar, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to=services.uploader.Uploader.user_cover_image, verbose_name='cover image'),
        ),
    ]
