# Generated by Django 4.2.7 on 2024-07-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='basket',
        ),
    ]
